# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowers_name', models.CharField(max_length=255, unique=True)),
                ('color_flowers', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to=b'')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('1', 'Roze'), ('2', 'Tulpan')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlowersPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowers_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_flowers.Flowers')),
            ],
        ),
    ]
