# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Distributor Price',
                'verbose_name_plural': 'Distributor Prices',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowers_name', models.CharField(max_length=255, unique=True)),
                ('color_flowers', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to=b'')),
                ('date_created', models.DateField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type_flowers', models.CharField(choices=[('0', 'Roze'), ('1', 'Tulip')], max_length=50)),
                ('discount', models.CharField(choices=[('0', 'Yes'), ('1', 'No')], max_length=3)),
            ],
            options={
                'verbose_name': 'Flower',
                'verbose_name_plural': 'Flowers',
            },
        ),
        migrations.CreateModel(
            name='FlowersPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_price', to='site_flowers.Flowers')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_order', models.DateField(verbose_name='Time Delivery')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('count', models.PositiveIntegerField(verbose_name='Count Flowers')),
                ('delivery', models.CharField(choices=[('0', 'Yes'), ('1', 'No')], max_length=3)),
                ('delivery_address', models.CharField(max_length=100)),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='site_flowers.Flowers')),
            ],
        ),
        migrations.AddField(
            model_name='distributorprice',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_price', to='site_flowers.Flowers'),
        ),
    ]
