# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'verbose_name': 'Flower', 'verbose_name_plural': 'Flowers'},
        ),
        migrations.AlterModelOptions(
            name='flowersprice',
            options={'verbose_name': 'FlowerPrice', 'verbose_name_plural': 'FlowersPrice'},
        ),
        migrations.AlterField(
            model_name='flowers',
            name='type',
            field=models.CharField(choices=[('1', 'Roze'), ('2', 'Tulip')], max_length=50),
        ),
    ]
